insert into Cards(DeckId,[Name],Flavourtext,attr1,attr2,attr3,attr4,attr5,Imagepath)
values (0,'Gideon', 'Hero at Akros, Leader of the gatewatch, and ally of Zendikar',12,8,6,10,2,'/Images/Gideon.jpg')
values (0,'Jace', 'Mind mage scholar of Vryn, Investigated anomalies on innistrad and lost himself on ixalan',15,12,6,1,10,'/Images/Jace.jpg')
values (0,'Chandra','Daughter of outlaw artificers on kaladesh, fueled by rage at their authorities',15,17,6,7,3,'/Images/Chandra.jpg')
values (0,'Nissa','Elf of zendikar, attuned to the land and all its inhabitants',13,11,7,6,5,'/Images/Nissa.jpg')
values (0,'Liliana','Ascendant necromancer who made pacts for power with several demons, killing them all',15,12,7,8,7,'/Images/Liliana.jpg')
values (0,'Ajani','Part of the nacatl pride on alara, valiant protector who joined the gatewatch',15,12,6,9,2,'/Images/Ajani.jpg')
values (0,'Nicol Bolas','Elder dragon seeking omnipotence and omniscience to ascend to godhood',28,6,8,12,12,'/Images/Bolas.jpg')
values (0,'Ugin', 'Spirit elder dragon, brother and rival to Bolas, Helped stop bolas ascending',7,2,8,8,12,'/Images/Ugin.jpg')
values (0,'Tezzeret','Master artificer from alara. Although human, he is more machine than man',14,8,6,6,8,'/Images/Tezzeret.jpg')
values (0,'Teferi','Temporal mage from the isle of zalphir, which he sent out of time for its protection',16,8,6,4,10,'/Images/Teferi.jpg')
values (0,'Karn','Sentient silver golem created by the nigh-omniscient artificer Urza',24,4,7,8,7,'/Images/Karn')
values (0,'Ob Nixilis','Demon of Zendikar who uses death magic to crush the weak',)